export default async function Sitemap() {
    const ItemSlug = [
      "midna-twilight-princess-statue-or-zelda-fan-art-by-oxo3d",
      "do-s-statue-or-one-punch-fan-art-by-oxo3d",
      "meowscarada-statue-or-pokemon-fan-art-by-officer-rhu",
      "psylocke-statue-or-x-man-fan-art-by-yan-h",
      "nico-robin-statue-or-one-piece-fan-art-by-oxo3d",
      "lucy-statue-or-cyberpunk2077-fan-art-by-oxo3d",
      "sister-repentia-statue-or-40k-fan-art-by-oxo3d",
      "jessie-and-meowth-statue-or-pokemon-fan-art-by-oxo3d",
      "lelith-hesperax-statue-or-40k-fan-art-by-oxo3d",
      "purah-statue-or-zelda-fan-art-by-oxo3d",
      "lara-croft-statue-or-tomb-raider-fan-art-by-oxo3d",
      "nami-statue-or-one-piece-fan-art-by-oxo3d",
      "yennefer-statue-or-the-witcher-fan-art-by-oxo3d",
      "mavis-waifu-statue-or-hotel-transylvania-fan-art-by-oxo3d",
      "moxxi-statue-or-borderlands-fan-art-by-oxo3d",
      "karlach-statue-or-baldur-s-gate-3-fan-art-by-oxo3d",
      "mara-jade-statue-or-star-wars-fan-art-by-oxo3d",
      "chel-statue-or-the-road-to-eldorado-fan-art-by-oxo3d",
      "barbarian-waifu-statue-or-original-fan-art-by-oxo3d",
      "cyberpunk-waifu-statue-or-cyberpunk2077-fan-art-by-oxo3d",
      "jessie-waifu-statue-or-toy-story-fan-art-by-oxo3d",
      "hermione-granger-statue-or-harry-potter-fan-art-by-oxo3d",
      "harley-quinn-statue-or-dc-fan-art-by-oxo3d",
      "tifa-statue-or-final-fantasy-fan-art-by-e-s-monster",
      "oze-maki-statue-or-fire-force-fan-art-by-e-s-monster",
      "ada-wang-statue-or-resident-evil-fan-art-by-e-s-monster",
      "red-monika-statue-or-battle-chasers-fan-art-by-e-s-monster",
      "chunli-bikini-statue-or-street-fighter-fan-art-by-e-s-monster",
      "ryuko-matoi-statue-or-kill-la-kill-fan-art-by-e-s-monster",
      "satsuki-kiryuin-statue-or-kill-la-kill-fan-art-by-e-s-monster",
      "yamato-statue-or-one-piece-fan-art-by-e-s-monster",
      "motoko-kusanagi-statue-or-ghost-in-the-shell-fan-art-by-e-s-monster",
      "malenia-statue-or-elden-ring-fan-art-by-ca3dart",
      "cammy-statue-or-street-fighter-fan-art-by-e-s-monster",
      "auska-statue-or-evangelion-fan-art-by-e-s-monster",
      "spider-gwen-statue-or-spider-verse-fan-art-by-e-s-monster",
      "rei-ayanami-statue-or-evangelion-fan-art-by-e-s-monster",
      "samus-aran-statue-or-metroid-fan-art-by-e-s-monster",
      "lulu-statue-or-final-fantasy-fan-art-by-e-s-monster",
      "triss-merigold-statue-or-the-witcher-fan-art-by-e-s-monster",
      "coven-evelynn-statue-or-league-of-legends-fan-art-by-e-s-monster",
      "felicia-hardy-statue-or-marvel-fan-art-by-e-s-monster",
      "felicia-statue-or-darkstalkers-fan-art-by-e-s-monster",
      "morrigan-aensland-statue-or-darkstalkers-fan-art-by-e-s-monster",
      "tear-halibe-statue-or-bleach-fan-art-by-e-s-monster",
      "jessica-rabbit-statue-or-who-framed-roger-rabbit-fan-art-by-e-s-monster",
      "2b-nier-statue-or-nier-automata-fan-art-by-e-s-monster",
      "velma-statue-or-scooby-doo-fan-art-by-e-s-monster",
      "karlach-statue-or-baldur-s-gate-3-fan-art-by-torrida-minis",
      "raven-statue-or-dc-fan-art-by-e-s-monster",
      "tauriel-statue-or-the-hobbit-fan-art-by-vx-labs",
      "iron-widow-statue-or-marvel-fan-art-by-vx-labs",
      "supergirl-statue-or-dc-fan-art-by-vx-labs",
      "scarlet-witch-statue-or-marvel-fan-art-by-vx-labs",
      "harley-quinn-statue-or-dc-fan-art-by-vx-labs",
      "the-wasp-statue-or-marvel-fan-art-by-vx-labs",
      "2bunny-statue-or-nier-automata-fan-art-by-rushzilla",
      "bowsette-statue-or-super-mario-fan-art-by-rushzilla",
      "dom-midna-statue-or-the-legend-of-zelda-fan-art-by-rushzilla",
      "dom-urbosa-statue-or-the-legend-of-zelda-fan-art-by-rushzilla",
      "amazon-statue-or-dragon-s-crown-fan-art-by-rushzilla",
      "sorceress-statue-or-dragon-s-crown-fan-art-by-rushzilla",
      "ghislaine-statue-or-mushoku-tensei-fan-art-by-rushzilla",
      "kim-possible-statue-or-kim-possible-fan-art-by-rushzilla",
      "lady-dimitrescu-statue-or-resident-evil-fan-art-by-rushzilla",
      "urbosa-statue-or-the-legend-of-zelda-fan-art-by-rushzilla",
      "zelda-statue-or-the-legend-of-zelda-fan-art-by-rushzilla",
      "yor-statue-or-spy-x-family-fan-art-by-rushzilla",
      "ryuko-statue-or-kill-la-kill-fan-art-by-rushzilla",
      "lady-cassandra-nsfw-statue-or-fantasy-universe-fan-art-by-ritual-casting",
      "purah-statue-or-the-legend-of-zelda-fan-art-by-rushzilla",
      "elvira-statue-or-mistress-of-the-dark-fan-art-by-texelion",
      "loona-statue-or-helluva-boss-fan-art-by-anyone-nsfw",
      "princess-bowsette-statue-or-super-mario-fan-art-by-officer-rhu",
      "wendy-s-statue-or-wendys-fan-art-by-officer-rhu",
      "frankie-foster-statue-or-foster-s-home-fan-art-by-officer-rhu",
      "minamoto-no-raikou-statue-or-jiangshi-fan-art-by-officer-rhu",
      "suu-statue-or-monster-musume-fan-art-by-officer-rhu",
      "toriel-goat-statue-or-undertale-universe-fan-art-by-officer-rhu",
      "cathyl-statue-or-monster-musume-fan-art-by-officer-rhu",
      "kassandra-statue-or-assassin-s-creed-fan-art-by-momoji3d",
      "gwen-statue-or-spider-man-fan-art-by-officer-rhu",
      "millie-statue-or-helluva-boss-fan-art-by-officer-rhu",
      "delphox-thicc-statue-or-pokemon-fan-art-by-officer-rhu",
      "roxanne-statue-or-five-nights-at-freddy-s-fan-art-by-anyone-nsfw",
      "ahsoka-statue-or-star-wars-fan-art-by-digital-dark",
      "mandalorian-girl-statue-or-star-wars-fan-art-by-digital-dark",
      "leia-statue-or-star-wars-fan-art-by-digital-dark",
      "darth-talon-statue-or-star-wars-fan-art-by-digital-dark",
      "misty-statue-or-pokemon-fan-art-by-digital-dark",
      "jessie-and-meowth-statue-or-pokemon-fan-art-by-digital-dark",
      "egyptian-catgirl-statue-or-original-fan-art-by-digital-dark",
      "barmaid-statue-or-original-fan-art-by-digital-dark",
      "student-zelda-statue-or-the-legend-of-zelda-fan-art-by-digital-dark",
      "furry-kitty-nekomimi-statue-or-original-fan-art-by-digital-dark",
      "wednesday-older-statue-or-the-addams-family-fan-art-by-digital-dark",
      "elsa-and-olaf-statue-or-frozen-fan-art-by-digital-dark",
      "orc-girl-statue-or-world-of-warcraft-fan-art-by-digital-dark",
      "shibari-girl-statue-or-original-fan-art-by-digital-dark",
      "aunt-cass-statue-or-big-hero-6-fan-art-by-digital-dark",
      "bad-wolf-statue-or-puss-in-bootsfan-art-by-anyone-nsfw",
      "dana-deer-statue-or-original-fan-art-by-anyone-nsfw",
      "loona-halloween-statue-or-helluva-boss-fan-art-by-officer-rhu",
      "teela-statue-or-masters-of-the-universe-fan-art-by-yan-h",
      "evil-lyn-statue-or-masters-of-the-universe-fan-art-by-ca3dart",
      "princess-peach-statue-or-super-mario-fan-art-by-officer-rhu",
      "loona-nsfw-statue-or-helluva-boss-fan-art-by-nonotoys",
      "krystal-fox-statue-or-star-fox-fan-art-by-azerama",
      "xena-statue-or-xena-warrior-princess-fan-art-by-ca3dart",
      "wednesday-statue-or-the-addams-family-fan-art-by-exclusive3dprints",
      "houndoom-nsfw-statue-or-pokemon-fan-art-by-evil-crivl",
      "diva-statue-or-overwatch-fan-art-by-digital-dark",
      "sarabi-statue-or-the-lion-king-fan-art-by-evil-crivl",
      "lucario-statue-or-pokemon-fan-art-by-officer-rhu",
      "ankha-statue-or-animal-crossing-fan-art-by-officer-rhu",
      "mal0-statue-or-scp-fan-art-by-evil-crivl",
      "ciri-statue-or-the-witcher-fan-art-by-oxo3d",
      "ranni-statue-or-elden-ring-fan-art-by-dinamuuu3d",
      "juri-statue-or-street-fighter-fan-art-by-rushzilla",
      "chun-li-statue-or-street-fighter-fan-art-by-rushzilla",
      "cammy-bikini-statue-or-street-fighter-fan-art-by-e-s-monster",
      "bonnie-bovine-statue-or-monster-musume-fan-art-by-officer-rhu",
      "zombina-monster-girl-statue-or-monster-musume-fan-art-by-officer-rhu",
      "centorea-statue-or-monster-musume-fan-art-by-officer-rhu",
      "yoruichi-shihouin-statue-or-bleach-fan-art-by-officer-rhu",
      "lopunny-tied-statue-or-pokemon-fan-art-by-officer-rhu",
      "shygal-statue-or-sper-mario-fan-art-by-officer-rhu",
      "vex-statue-or-league-of-legends-fan-art-by-officer-rhu",
      "gardevoir-baseball-statue-or-pokemon-fan-art-by-officer-rhu",
      "hellhound-monster-girl-statue-or-original-fan-art-by-officer-rhu",
      "arcanine-statue-or-pokemon-fan-art-by-anyone-nsfw",
      "felicia-stacked-statue-or-darkstalkers-fan-art-by-officer-rhu",
      "rouge-statue-or-sonic-the-hedgehog-fan-art-by-anyone-nsfw",
      "maid-marian-statue-or-robin-hood-fan-art-by-anyone-nsfw",
      "renamon-statue-or-digimon-fan-art-by-anyone-nsfw",
      "chel-statue-or-the-road-to-eldorado-fan-art-by-digital-dark",
      "karlach-statue-or-baldur-s-gate-3-fan-art-by-digital-dark",
      "daphne-blake-statue-or-scooby-doo-fan-art-by-digital-dark",
      "battle-thick-2-statue-or-40k-fan-art-by-digital-dark",
      "yvrainy-statue-or-40k-fan-art-by-digital-dark",
      "sailor-girls-statue-or-sailor-moon-fan-art-by-digital-dark",
      "bride-girls-statue-or-zelda-nier-fan-art-by-digital-dark",
      "raven-statue-or-dc-fan-art-by-digital-dark",
      "mavis-or-wednesday-statue-or-hotel-and-addams-fan-art-by-digital-dark",
      "rebecca-statue-or-cyberpunk-edgerunners-fan-art-by-digital-dark",
      "goblin-queen-statue-or-x-men97-fan-art-by-pop-totem",
      "eve-statue-or-stellar-blade-fan-art-by-pop-totem",
      "x-23-statue-or-x-men-fan-art-by-pop-totem",
      "machiko-noguchi-statue-or-predator-fan-art-by-pop-totem",
      "red-sonja-statue-or-marvel-fan-art-by-pop-totem",
      "black-widow-statue-or-marvel-fan-art-by-pop-totem",
      "lucia-statue-or-gta-6-fan-art-by-pop-totem",
      "cammy-white-statue-or-street-fighter-fan-art-by-pop-totem",
      "emperor-of-mankind-miniature-or-40k-fan-art-by-3dartguy",
      "diseased-reaper-miniature-or-40k-fan-art-by-3dartguy",
      "secret-agent-miniature-or-40k-fan-art-by-3dartguy",
      "tinker-bell-goth-statue-or-peter-pan-fan-art-by-officer-rhu",
      "fluttershy-pony-statue-or-my-little-pony-fan-art-by-officer-rhu",
      "musashi-wedding-statue-or-azur-lane-fan-art-by-officer-rhu",
      "glaceon-statue-or-pokemon-fan-art-by-officer-rhu",
      "judy-statue-or-cyberpunk2077-fan-art-by-h3ll",


    ];
    const Style = [
      "?style=SFW",
      "?style=NSFW",
      "?style=Futa",
    ]
    const baseUrl = "https://sultry3dprints.com/products/";
    const baseUrlStyle = "https://sultry3dprints.com/";

    const sitemapStyle = Style.map((packName) => {
      const url = baseUrlStyle + packName;
      return {
        url,
        lastModified: new Date(),
      };
    });
    const sitemapItems = ItemSlug.map((packName) => {
      const url =  baseUrl + packName;
      return {
        url,
        lastModified: new Date(),
      };
    });
  
    // Combine both arrays
    const sitemap = [
      {
          url: "https://sultry3dprints.com",
          lastModified: new Date(),
      },
      ...sitemapStyle,
      ...sitemapItems,
  ];
    
    return sitemap;
  }