export default async function Sitemap() {
    const stlPackNames = [
      "diva-overwatch-3d-printed-resin-statue-fan-art-or-digital-dark",
      "aunt-cass-big-hero-6-3d-printed-resin-statue-fan-art-by-digital-dark",
      "wednesday-older-3d-printed-resin-statue-fan-art-by-digital-dark",
      "furry-kitty-nekomimi-3d-printed-resin-statue-fan-or-by-digital-dark",
      "elsa-and-olaf-3d-printed-resin-statue-fan-art-by-digital-dark",
      "student-zelda-3d-printed-resin-statue-fan-art-by-digital-dark",
      "barmaid-3d-printed-resin-statue-fan-art-by-digital-dark",
      "egyptian-catgirl-3d-printed-resin-statue-fan-art-by-digital-dark",
      "jessie-and-meowth-pokemon-3d-printed-resin-statue-fan-art-by-digital-dark",
      "misty-pokemon-3d-printed-resin-statue-fan-art-by-digital-dark",
      "sister-of-battle-warhammer-40k-3d-printed-resin-statue-fan-art-by-digital-dark",
      "darth-talon-star-wars-3d-printed-resin-statue-fan-art-by-digital-dark",
      "minamoto-no-raikou-jiangshi-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "suu-monster-musume-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "princess-bowsette-mario-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "toriel-goat-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "frankie-foster-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "delphox-thicc-pokemon-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "gwen-spider-man-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "dana-deer-3d-printed-resin-statue-fan-art-by-anyone-nsfw",
      "bad-wolf-3d-printed-resin-statue-fan-art-by-anyone-nsfw",
      "loona-helluva-boss-3d-printed-resin-statue-fan-art-by-anyone-nsfw",
      "malenia-elden-ring-3d-printed-resin-statue-fan-art-by-ca3dart",
      "lucario-pokemon-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "kassandra-assassin-s-creed-3d-printed-resin-statue-fan-art-by-momoji3d",
      "millie-helluva-boss-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "loona-halloween-helluva-boss-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "leia-star-wars-3d-printed-resin-statue-fan-art-by-digital-dark",
      "ahsoka-star-wars-3d-printed-resin-statue-fan-art-by-digital-dark",
      "mandalorian-girl-star-wars-3d-printed-resin-statue-fan-art-by-digital-dark",
      "houndoom-nsfw-pokemon-3d-printed-resin-statue-fan-art-by-evil-crivl",
      "karlach-baldur-s-gate-3-3d-printed-resin-statue-fan-art-by-torrida-minis",
      "elvira-3d-printed-resin-statue-fan-art-by-texelion",
      "princess-peach-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "wendy-s-3d-printed-resin-statue-fan-art-by-officer-rhu",
      "warrior-3d-printed-resin-statue-fan-art-by-futafantasy",
      "shibari-girl-3d-printed-resin-statue-fan-art-by-digital-dark",
      "orc-girl-3d-printed-resin-statue-fan-art-by-digital-dark",
      "ranni-3d-printed-resin-statue-fan-art-by-dinamuuu3d",
      "lady-cassandra-nsfw-3d-printed-resin-statue-fan-art-by-ritual-casting",
      "purah-3d-printed-resin-statue-fan-art-by-rushzilla",
      "ryuko-3d-printed-resin-statue-fan-art-by-rushzilla",
      "yor-3d-printed-resin-statue-fan-art-by-rushzilla",
      "zelda-3d-printed-resin-statue-fan-art-by-rushzilla",
      "urbosa-3d-printed-resin-statue-fan-art-by-rushzilla",
      "kim-possible-3d-printed-resin-statue-fan-art-by-rushzilla",
      "juri-3d-printed-resin-statue-fan-art-by-rushzilla",
      "ghislaine-3d-printed-resin-statue-fan-art-by-rushzilla",
      "sorceress-dragon-s-crown-3d-printed-resin-statue-fan-art-by-rushzilla",
      "amazon-dragon-s-crown-3d-printed-resin-statue-fan-art-by-rushzilla",
      "dom-urbosa-3d-printed-resin-statue-fan-art-by-rushzilla",
      "dom-midna-3d-printed-resin-statue-fan-art-by-rushzilla",
      "chun-li-3d-printed-resin-statue-fan-art-by-rushzilla",
      "bowsette-3d-printed-resin-statue-fan-art-by-rushzilla",
      "2bunny-3d-printed-resin-statue-fan-art-by-rushzilla",
      "the-wasp-3d-printed-resin-statue-fan-art-by-vx-labs",
      "harley-quinn-3d-printed-resin-statue-fan-art-by-vx-labs",
      "scarlet-witch-3d-printed-resin-statue-fan-art-by-vx-labs",
      "supergirl-3d-printed-resin-statue-fan-art-by-vx-labs",
      "tauriel-the-hobbit-3d-printed-resin-statue-fan-art-by-vx-labs",
      "iron-widow-3d-printed-resin-statue-fan-art-by-vx-labs",
      "velma-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "raven-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "2b-nier-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "jessica-rabbit-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "tear-halibe-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "morrigan-aensland-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "felicia-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "felicia-hardy-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "coven-evelynn-3d-printed-resin-statue-fan-or-by-e-s-monster",
      "triss-merigold-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "lulu-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "samus-aran-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "rei-ayanami-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "spider-gwen-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "auska-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "cammy-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "motoko-kusanagi-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "yamato-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "satsuki-kiryuin-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "ryuko-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "chunli-bikini-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "red-monika-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "cammy-bikini-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "ada-wang-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "oze-maki-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "tifa-3d-printed-resin-statue-fan-art-by-e-s-monster",
      "harley-quinn-3d-printed-resin-statue-fan-art-by-oxo3d",
      "hermione-granger-3d-printed-resin-statue-fan-art-by-oxo3d",
      "jessie-waifu-3d-printed-resin-statue-fan-art-by-oxo3d",
      "cyberpunk-waifu-3d-printed-resin-statue-fan-art-by-oxo3d",
      "barbarian-waifu-3d-printed-resin-statue-fan-art-by-oxo3d",
      "chel-3d-printed-resin-statue-fan-art-by-oxo3d",
      "ciri-3d-printed-resin-statue-fan-art-by-oxo3d",
      "karlach-3d-printed-resin-statue-fan-art-by-oxo3d",
      "mara-jade-3d-printed-resin-statue-fan-art-by-oxo3d",
      "moxxi-3d-printed-resin-statue-fan-art-by-oxo3d",
      "mavis-waifu-3d-printed-resin-statue-fan-art-by-oxo3d",
      "yennefer-3d-printed-resin-statue-fan-art-by-oxo3d",
      "nami-3d-printed-resin-statue-fan-art-by-oxo3d",
      "lara-croft-3d-printed-resin-statue-fan-art-by-oxo3d",
      "purah-3d-printed-resin-statue-fan-art-by-oxo3d",
      "midna-twilight-princess-3d-printed-resin-statue-fan-art-by-oxo3d",
      "lelith-hesperax-3d-printed-resin-statue-fan-art-by-oxo3d",
      "jessie-and-meowth-3d-printed-resin-statue-fan-art-by-oxo3d",
      "sister-repentia-3d-printed-resin-statue-fan-art-by-oxo3d",
      "dos-3d-printed-resin-statue-fan-art-by-oxo3d",
      "lucy-3d-printed-resin-statue-fan-art-by-oxo3d",
      "nico-robin-3d-printed-resin-statue-fan-art-by-oxo3d",
      
      
     
      
  
      
    ];
    
    const baseUrl = "https://sultry3dprints.com/products/";
  
    const sitemapItems = stlPackNames.map((packName) => {
      const url = baseUrl + packName;
      return {
        url,
        lastModified: new Date(),
      };
    });
  
    sitemapItems.unshift({
      url: "https://sultry3dprints.com",
      lastModified: new Date(),
    });
  
    return sitemapItems;
  }